FROM memoryleak/php:7.1
RUN apk add --no-cache php7-xdebug && \
	sed -i 's/;zend_extension=xdebug.so/zend_extension=xdebug.so/' /etc/php7/conf.d/xdebug.ini
COPY php-entrypoint /bin/
ENTRYPOINT ["php-entrypoint"]
WORKDIR /var/www/html
CMD ["php"]