FROM memoryleak/php:7.1
RUN apk add --no-cache wget patch git && \
	wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet --install-dir /usr/local/bin --filename composer

ENTRYPOINT ["composer"]